return {
  ensure_installed = {
    "bash",
    "csv",
    "cue",
    "dockerfile",
    "editorconfig",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "go",
    "gpg",
    "hcl",
    "helm",
    "html",
    "http",
    "ini",
    "java",
    "javascript",
    "jinja",
    "jinja_inline",
    "jq",
    "json",
    "lua",
    "luadoc",
    "make",
    "markdown",
    "markdown_inline",
    "nginx",
    "passwd",
    "powershell",
    "printf",
    "promql",
    "properties",
    "proto",
    "puppet",
    "python",
    "regex",
    "rego",
    "requirements",
    "sql",
    "ssh_config",
    "tmux",
    "typescript",
    "vim",
    "vimdoc",
    "xml",
    "yaml",
  },

  highlight = {
    enable = true,
    use_languagetree = true,
  },

  indent = { enable = true },

  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "<C-space>",
      node_incremental = "<C-space>",
      scope_incremental = false,
      node_decremental = "<bs>",
    },
  },
}
